name: publish

on:
  release:
    types:
      - created
env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  build-linux:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go Lang
        uses: actions/setup-go@v1
        with:
          go-version: '1.19'
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.0
      - name: Build
        run: make build && mv constellation-cli constellation-cli-linux
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./constellation-cli-linux
          asset_name: constellation-cli-linux
          asset_content_type: application/zip
  build-macos:
    runs-on: macos-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go Lang
        uses: actions/setup-go@v1
        with:
          go-version: '1.19'
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.0
      - name: Build
        run: make build && mv constellation-cli constellation-cli-macos
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./constellation-cli-macos
          asset_name: constellation-cli-macos
          asset_content_type: application/zip
  build-windows:
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go Lang
        uses: actions/setup-go@v1
        with:
          go-version: '1.19'
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.0
      - name: Build
        run: |
         make build
         mv constellation-cli constellation-cli-windows.exe
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./constellation-cli-windows.exe
          asset_name: constellation-cli-windows.exe
          asset_content_type: application/zip
