name: tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go Lang
        uses: actions/setup-go@v1
        with:
          go-version: '1.19'
      - name: Run tests
        run: make test
